* Install

The software system is consists of different deployables. Currently, there are 3 deployables, but the system can
easily be extended:
1. Server, which has an api that 'speaks dwc'
2. Admin web client, which can be used to manage users and datasets
3. Occurrences web client, which is a web client for researchers to add observations ('occurrences')

In general to have the software system up and running properly, one should add a reverse proxy (nginx, apache, ...) in front of the three deployables:

#+BEGIN_SRC deployment-diagram
                                         +------------------+
                                         |                  |
                                         |  client browser  |
                                         |                  |
                                         +--------+---------+
                                                  |
                                                  | https://[domain]/[path]
                                                  |
+-------------------------------------------------|--------------------------------------------------+
|                                                 |                                                  |
|                                      +----------v-----------+                                      |
|                                      |                      |                                      |
|                                      |    reverse proxy     |                                      |
|                                      |                      |                                      |
|                             +--------+  (nginx/apache/...)  +--------+                             |
|                             |        |                      |        |                             |
|                             |        +----------+-----------+        |                             |
|          [path:/occurrences]|                   |                    |[path:/api/]                 |
|                             |                   |[path:/admin]       |                             |
|                             |                   |                    |                             |
|                             |                   |                    |                             |
|                             |                   |                    |http://localhost:8080/api/   |
|  +--------------------------v-+   +-------------v--------------+   +-v--------------------------+  |
|  |                            |   |                            |   |                            |  |
|  |   occurrences web client   |   |      admin web client      |   |      smalldata server      |  |
|  |                            |   |                            |   |                            |  |
|  +----------------------------+   +----------------------------+   +----------------------------+  |
|                                                                                                    |
+----------------------------------------------------------------------------------------------------+
#+END_SRC


** Reverse proxy

The reverse proxy needs at least these paths:
- ~/occurrences~ \to location of the occurrences web client (e.g. ~/var/www/html/occurrences~ on debian based systems)
- ~/admin~ \to location of the admin web client (e.g. ~/var/www/html/admin~ on debian based systems)
- ~/api/~ \to proxy pass to where the server runs (e.g. ~http://localhost:8080/~ with the default config)


*** nginx

An example config for nginx:

#+BEGIN_SRC nginx-config
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		proxy_set_header Host $host;
		proxy_redirect off;

		proxy_pass http://localhost:8080/;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $server_name;
	}

	location /api/ {
		rewrite  ^  $request_uri;
      		rewrite ^/api/(.*) $1 break;
        	return 400;
		proxy_pass http://localhost:8080/api/$uri;
	}

	location /occurrences {
		try_files $uri $uri/ =404;
	}

	location /admin {
		try_files $uri $uri/ =404;
	}
}
#+END_SRC

** Server

*** Method 1: from the server application image

The images of the server are available on http://smalldata.obis.org/images/ :
1. get the last one
2. unzip it in the directory you want to install it
3. make sure the config is ok.
   - A sample config can be found in [[https://github.com/iobis/smalldata/blob/master/server/config/config.json][the source code]]
   - check the [[docs/server-config.md][config info]]
4. run ~./bin/smalldata.server -conf config/config.json~ from the root of the application.
   - on windows: use ~./bin/smalldata.server.bat -conf config/config.json~
   - check the config location! You may change the location of the config file

*** Method 2: using gradle

** Web clients

...


