openapi: 3.0.0
info:
  version: 1.0.0
  title: Small Data Swagger
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
  - url: http://localhost:8008/
paths:
  /api/datasets:
    get:
      summary: get all datasets
      operationId: getDatasets
      tags:
        - datasets
      responses:
        200:
          description: array with datasets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'dataset.yaml#/Dataset'
  /api/datasets/{datasetRef}:
    get:
      summary: get one dataset by ref
      operationId: getOneDataset
      parameters:
        - name: datasetRef
          in: path
          description: unique reference of the dataset
          required: true
          schema:
            type: string
      tags:
        - datasets
      responses:
        200:
          description: dataset information and metadata
          content:
            application/json:
              schema:
                $ref: 'dataset.yaml#/Dataset'
  /api/users/{userRef}/dwca:
    get:
      summary: get all dwca records for a user
      operationId: getDwcaRecords
      parameters:
        - name: userRef
          in: path
          description: unique reference (id) of the user
          required: true
          schema:
            type: string
      tags:
        - DWCA
      responses:
        200:
          description: array with dwca records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DWCA"
                example:
                  - core: occurrence
                    occurrence:
                      dwcg:
                        habitat: Bruges
  /api/users/{userRef}/dwca/{dwcaId}:
    get:
      summary: get one dwca record for a user
      operationId: getDwcaRecord
      parameters:
        - name: userRef
          in: path
          description: unique reference (id) of the user
          required: true
          schema:
            type: string
        - name: dwcaId
          in: path
          description: unique reference (id) of the dwca record
          required: true
          schema:
            type: string
      tags:
        - DWCA
      responses:
        200:
          description: dwca record
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DWCA"

  /api/login:
    post:
      summary: get jwt token
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: login succesful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: cannot login
  /api/status:
    get:
      summary: get status of the server
      operationId: getStatus
      tags:
        - info
      responses:
        200:
          description: application running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/rss/{periodicity}:
    get:
      summary: rss feed
      operationId: getRss
      parameters:
        - name: periodicity
          in: path
          description: periodicity of the rss feed
          required: true
          schema:
            type: string
            enum: ['hourly', 'daily', 'weekly', 'monthly', 'yearly', 'all']
            example: 'weekly'
      tags:
        - rss
      responses:
        200:
          description: received rss
          content:
            application/xml+rss: {}
  /api/dwca/{dataset}:
    get:
      summary: get dwca zip
      operationId: getDWCA
      parameters:
        - name: dataset
          in: path
          description: ref of the dataset
          required: true
          schema:
            type: string
      tags:
        - dwca
      responses:
        200:
          description: got dwca file
          content:
            application/zip: {}
  /api/dwca/:
    post:
      summary: post new data to small data occurences
      operationId: postDWCA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DWCA"

      tags:
        - dwca
      responses:
        200:
          description: new occurences data created and stored
          content:
            application/json: {}
        405:
          description: invalid input

components:
  schemas:
    Status:
      type: object
      properties:
        title:
          type: string
          example: 'swaggered application'
        status:
          type: string
          enum: ['OK', 'error']
          example: 'OK'
    DWCA:
      type: object
      description: dwca record
      properties:
        core:
          type: string
          enum: ['occurrence', 'taxon', 'event', 'emof']
          example: 'occurrence'
        occurrence:
          # $ref: 'http://smalldata.obis.org/spec/occurrence.yaml#/Occurrence' # "./spec/occurrence.yaml#/Occurrence"
          $ref: "occurrence.yaml#/Occurrence"
        taxon:
          $ref: "taxon.yaml#/Taxon"
        event:
          $ref: "event.yaml#/Event"
        emof:
          $ref: "emof.yaml#/EMOF"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
