version: 2

jobs:
  test-front-end:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Front End Unit Tests
          command: yarn test
  test-backend:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "dependencies.lockfile" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-
      - run: server/gradlew test
      - save_cache:
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum "dependencies.lockfile" }}
          paths:
            - ~/server/.gradle

workflows:
  version: 2
  workflow:
    jobs:
      - test-front-end
      - test-backend
