version: 2

jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch-node
    steps:
      - checkout
      - run:
          name: Install Front End Deps
          command: yarn install --frozen-lockfile
      - run:
          name: Run Unit Tests
          command: yarn test:ci
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout  
      - run:
          name: Deploy Over SSH
          command: |
            scp -r ./info "$SSH_USER@$SSH_HOST:~"

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
