version: 2

jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - run:
          name: Install Front End Deps
          command: yarn install --frozen-lockfile
      - run:
          name: Run Unit Tests
          command: yarn test:ci

workflows:
  version: 2
  workflow:
    jobs:
      - test
