version: 2

jobs:
  test-front-end:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Front End Unit Tests
          command: yarn test
  test-backend:
    working_directory: ~/server
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
    - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - gradle-repo-v1-{{ .Branch }}-{{ checksum "dependencies.lockfile" }}
          - gradle-repo-v1-{{ .Branch }}-
          - gradle-repo-v1-
    - save_cache:
        paths:
          - ~/.gradle
        key: gradle-repo-v1-{{ .Branch }}-{{ checksum "dependencies.lockfile" }}
    - run: cd server
    - run: gradle test

workflows:
  version: 2
  workflow:
    jobs:
      - test-front-end
      - test-backend
