version: 2

jobs:
  test-front-end:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Run Front End Unit Tests
          command: yarn test
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - server/.gradle

workflows:
  version: 2
  workflow:
    jobs:
      - test-front-end
