openapi: 3.0.0
info:
  version: 1.0.0
  title: Small Data Swagger
  license:
    name: MIT
servers:
  - url: http://localhost:8008/
  - url: http://localhost:8080/
paths:
  /api/status:
    get:
      summary: get status of the server
      operationId: getStatus
      tags:
        - info
      responses:
        200:
          description: application running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/rss/{periodicity}:
    get:
      summary: rss feed
      operationId: getRss
      parameters:
        - name: periodicity
          in: path
          description: periodicity of the rss feed
          required: false
          schema:
            type: string
      tags:
        - rss
      responses:
        200:
          description: received rss
          content:
            application/xml+rss: {}
  /api/occurence:
    post:
      summary: post new data to small data occurences
      operationId: postOccurence
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Occurence"
      tags:
        - occurences
      responses:
        200:
          description: new occurences data created and stored
          content:
            application/json: {}
        405:
          description: invalid input

components:
  schemas:
    Status:
      type: object
      properties:
        title:
          type: String
          example: 'swaggered application'
        status:
          type: String
          enum: ['OK', 'error']
          example: 'OK'
    DWC.Event:
      type: object
      required:
        - eventDate
      properties:
        eventDate:
          type: string
          format: date-time
        verbatimEventDate:
          type: string
        fieldNumber:
          type: string
    DWC.Identification:
      type: object
      properties:
        identificationQualifier:
          type: string
        identificationRemarks:
          type: string
        identifiedBy:
          type: string
    DWC.Location:
      type: object
      required:
        - decimalLongitude
        - decimalLatitude
      properties:
        decimalLongitude:
          type: number
          format: double
          minimum: -180
          maximum: 180
        decimalLatitude:
          type: number
          format: double
          minimum: -90
          maximum: 90
        verbatimCoordinates:
          type: string
        coordinateUncertaintyInMeters:
          type: number
          format: double
          minimum: 0
          exclusiveMinimum: true
        footprintWKT:
          type: string
        locality:
          type: string
        minimumDepthInMeters:
          type: number
          format: float
          minimum: 0
        maximumDepthInMeters:
          type: number
          format: float
          minimum: 0
        verbatimDepth:
          type: string
    EMOF.MeasurementOrFact:
      type: object
      required:
        - measurementType
        - measurementValue
      properties:
        measurementType:
          type: string
        measurementTypeID:
          type: string
        measurementValue:
          type: string
        measurementValueID:
          type: string
        measurementAccuracy:
          type: string
        measurementUnit:
          type: string
        measurementUnitID:
          type: string
        measurementMethod:
          type: string
        measurementRemarks:
          type: string
    DWC.Occurence:
      type: object
      required:
        - occurenceID
      properties:
        occurenceID:
          type: string
        occurenceStatus:
          type: string
          enum: ['absent', 'present']
        occurenceRemarks:
          type: string
        catalogNumber:
          type: string
        recordedBy:
          type: string
    DWC.Record:
      type: object
      required:
        - basisOfRecord
      properties:
        basisOfRecord:
          type: string
          enum: ['PreservedSpecimen', 'FossilSpecimen', 'LivingSpecimen', 'HumanObservation', 'MachineObservation']
        references:
          type: array
          items:
            type: string
            format: uri
        institutionCode:
          type: string
        collectionCode:
          type: string
    DWC.Taxon:
      type: object
      required:
        - scientificNameID
      properties:
        scientificNameID:
          type: string
        scientificName:
          type: string
    Occurence:
      type: object
      required:
        - location
        - taxon
        - occurence
        - event
        - record
      properties:
        location:
          $ref: "#/components/schemas/DWC.Location"
        taxon:
          $ref: "#/components/schemas/DWC.Taxon"
        occurence:
          $ref: "#/components/schemas/DWC.Occurence"
        event:
          $ref: "#/components/schemas/DWC.Event"
        record:
          $ref: "#/components/schemas/DWC.Record"
        identification:
          $ref: "#/components/schemas/DWC.Identification"
        measurementOrFact:
          $ref: "#/components/schemas/EMOF.MeasurementOrFact"
        custom:
          type: array
          items:
            type: object
            required:
              - term
              - value
            properties:
              term:
                type: string
              value:
                type: string
      additionalProperties: false
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
