openapi: 3.0.0
info:
  version: 1.0.0
  title: Small Data Swagger
  license:
    name: MIT
servers:
  - url: http://localhost:8008/
  - url: http://localhost:8080/
paths:
  /api/status:
    get:
      summary: get status of the server
      operationId: getStatus
      tags:
        - info
      responses:
        200:
          description: application running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/rss/{periodicity}:
    get:
      summary: rss feed
      operationId: getRss
      parameters:
        - name: periodicity
          in: path
          description: periodicity of the rss feed
          required: false
          schema:
            type: string
      tags:
        - rss
      responses:
        200:
          description: received rss
          content:
            application/xml+rss: {}

components:
  schemas:
    Status:
      type: object
      properties:
        title:
          type: String
          example: 'swaggered application'
        status:
          type: String
          enum: ['OK', 'error']
          example: 'OK'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
