* smalldata
** requirement
   1. ~node~ must be installed latest lts version (10.16.3 or higher)
   2. ~yarn~ must be installed lastest version
   3. Java 11 or higher must be installed on your system

** server
*** how to start during dev
    the api spec has been split into several files. However, due to some issues with relative paths and reading the specs,
    the different files need to be bundled into 1 spec file before running the server. In the root of the project:

    #+BEGIN_SRC shell
    yarn server:bundle-spec
    #+END_SRC

    This task can also be set to run before ~./gradlew run~ in your IDE. In intellij:
    1. upper right: drop down of the tasks
    2. ~edit configuration~
    3. ~server[run]~
    4. ~launch before~ (right bottom pane) -- ~+~
    5. ~Run npm script~
    6. choose the right ~package.json~, it's the one in the root of the project
    7. in ~scripts~: ~server:bundle-spec~

** web clients
   In the root of ~admin-app~ and ~occurrences-app~ there is package.json file with proxy configuration. Proxy config specifies the URL of server API.
   http://localhost:8080/ value is good for local development. If you want to run a development server against the non-local instance then update it.

   You can change the port on which development server of each application is running by updating ~.evn~ in the root of the ~*-app~ folder.

   - use ~yarn admin-app:start~ to start admin app
   - use ~yarn occurrences-app:start~ to start occurence app
   - use ~yarn start~ to start admin-app, occurrence-app and the server

** JWT
   call ocean expert social login from the web client:

   #+BEGIN_SRC shell
   https://oceanexpert.net/socialsignin/?callback=<callback-url>
   #+END_SRC

   callback-url will be called with a jwt query parameter, containing the token, e.g., if the callback-url is http://localhost:3000 (e.g. for testing/developing), after login, ocean expert will call http://localhost:3000?jwt=eyJ0eXAiOiJKV1Q...
   The validity and claims of the JWT can be parsed using http://jwt.io (contains username, email, profile picture, ...)
   test-account: kurt<dot>sys@moment-4<dot>be / 0ceanexpert

* links
  - [[https://create-react-app.dev/docs/proxying-api-requests-in-development][Proxying API Requests in Development]]
  - [[https://create-react-app.dev/docs/deployment/#building-for-relative-paths][Building for Relative Paths]]
  - [[https://create-react-app.dev/docs/deployment][Deployment]]
